Repository ExtendedXmlSerializer/home, pull requests merged in 2020-12, with the labels that each got.

#489 Attended to warnings.
  test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue477Tests_Extended.cs
Labels: continuous integration

#487 Fixed list support in `WithUnknownContent`
  src/ExtendedXmlSerializer/ExtensionModel/Content/UnknownContentHandlingExtension.cs
  test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue473Tests.cs
Labels: bug

#484 Added non-generic equivalent for `AddMigration`
  src/ExtendedXmlSerializer/ExtensionMethodsForXml.cs
  src/ExtendedXmlSerializer/ExtensionModel/Xml/MigrationsExtension.cs
  test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue483Tests.cs
Labels: enhancement

#492 Applied serializer type check using `WithUnknownContent`
  src/ExtendedXmlSerializer/ContentModel/Members/FixedInstanceMemberSerialization.cs
  src/ExtendedXmlSerializer/ContentModel/Members/IInstanceMemberSerialization.cs
  src/ExtendedXmlSerializer/ContentModel/Members/InstanceMemberSerialization.cs
  src/ExtendedXmlSerializer/ContentModel/Members/MemberInnerContentHandler.cs
  src/ExtendedXmlSerializer/ExtensionModel/Content/UnknownContentHandlingExtension.cs
  test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue491Tests.cs
Labels: bug

#494 Added non-generic versions of `EnableImplicitTypingFrom*` methods
  src/ExtendedXmlSerializer/ExtensionMethodsForImplicitTyping.cs
Labels: enhancement

#495 Added `EnableImplicitTypingByInspecting<T>` extension method
  src/ExtendedXmlSerializer/ExtensionMethodsForImplicitTyping.cs
  src/ExtendedXmlSerializer/ExtensionModel/Types/Sources/InspectedPropertyTypes.cs
  test/ExtendedXmlSerializer.Tests/ExtensionModel/Types/Sources/InspectedPropertyTypesTests.cs
Labels: enhancement
