Repository ExtendedXmlSerializer/home, pull requests merged in 2020-09, with the labels that each got.

#430 Allowed `null` Namespace for Framework Types
  src/ExtendedXmlSerializer/ContentModel/Reflection/PartitionedTypeSpecification.cs
Labels: bug

#432 Allowed `null`/Empty Namespaces for Custom/Non-system Assemblies
  src/ExtendedXmlSerializer/ContentModel/Reflection/AssemblyPathParser.cs
  src/ExtendedXmlSerializer/ContentModel/Reflection/AssemblyTypePartitions.cs
  src/ExtendedXmlSerializer/ContentModel/Reflection/Classification.cs
  src/ExtendedXmlSerializer/ContentModel/Reflection/Types.cs
  test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue431Tests.cs
  test/ExtendedXmlSerializer.Tests/ContentModel/Reflection/TypePartsParserTests.cs
Labels: bug

#437 Removed Caching from Reference Resolution
  src/ExtendedXmlSerializer/ExtensionModel/References/References.cs
  test/ExtendedXmlSerializer.Tests.ReportedIssues/ExtendedXmlSerializer.Tests.ReportedIssues.csproj
  test/ExtendedXmlSerializer.Tests.ReportedIssues/ExtendedXmlSerializer.Tests.ReportedIssues.csproj.DotSettings
  test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue434Tests.cs
  test/ExtendedXmlSerializer.Tests.ReportedIssues/Issued434Tests_Extended.cs
Labels: bug

#444 Accounted for empty CDATA elements.
  src/ExtendedXmlSerializer/ExtensionModel/Xml/XmlReader.cs
  test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue442Tests.cs
  test/ExtendedXmlSerializer.Tests.ReportedIssues/Shared/Issue442/IDeviceTemplate.cs
  test/ExtendedXmlSerializer.Tests.ReportedIssues/Shared/Issue442/SiemensDeviceTemplate.cs
  test/ExtendedXmlSerializer.Tests.ReportedIssues/Shared/Issue442/WatchAndForceTableTemplate.cs
Labels: bug

#448 Accounted for successive CDATA blocks.
  src/ExtendedXmlSerializer/ExtensionModel/Xml/XmlReader.cs
  test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue445Tests.cs
  test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue447Tests.cs
Labels: bug

#450 Added test, removed assignment.
  src/ExtendedXmlSerializer/ExtensionModel/Xml/XmlElements.cs
  test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue443Tests.cs
Labels: housekeeping

#452 Introduced type-based serialization interception.
  src/ExtendedXmlSerializer/ContentModel/RuntimeSerializer.cs
  src/ExtendedXmlSerializer/ExtensionMethodsForContent.cs
  src/ExtendedXmlSerializer/ExtensionModel/Instances/ISerializationInterceptor.cs
  src/ExtendedXmlSerializer/ExtensionModel/Instances/SerializationActivator.cs
  src/ExtendedXmlSerializer/ExtensionModel/Instances/SerializationInterceptionExtension.cs
  src/ExtendedXmlSerializer/ExtensionModel/Instances/SerializationInterceptor.cs
  test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue451Tests.cs
  test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue451Tests_Reported.cs
Labels: enhancement
