Repository ExtendedXmlSerializer/home, pull requests merged in 2020-03, with the labels that each got.

#373 Added Sample code for question.
  test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue372Tests.cs
Labels: question

#376 Added test demonstrating private setters.
  test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue374Tests.cs
Labels: bug

#381 Fixed Caching Issues for Better Performance.
  src/ExtendedXmlSerializer/ContentModel/Members/TypeMembers.cs
  src/ExtendedXmlSerializer/ContentModel/Members/WritableMemberAccessors.cs
  test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue374Tests.cs
  test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue375Tests.cs
Labels: bug

#380 Added sample code.
  test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue377Tests.cs
Labels: documentation
