Repository ExtendedXmlSerializer/home, pull requests merged in 2020-10, with the labels that each got.

#456 Update NuGet API Key
  .build/appveyor.yml
Labels: continuous integration

#459 Use BenchmarkSwitcher
  test/ExtendedXmlSerializer.Tests.Performance/Program.cs
Labels: hacktoberfest-accepted, refactoring

#457 Update nuget packages
  src/ExtendedXmlSerializer/ExtendedXmlSerializer.csproj
  test/ExtendedXmlSerializer.Tests.Performance/Benchmarks.cs
  test/ExtendedXmlSerializer.Tests.Performance/ExtendedXmlSerializer.Tests.Performance.csproj
  test/ExtendedXmlSerializer.Tests.ReportedIssues/ExtendedXmlSerializer.Tests.ReportedIssues.csproj
  test/ExtendedXmlSerializer.Tests/ExtendedXmlSerializer.Tests.csproj
Labels: dependencies, hacktoberfest-accepted

#460 Update performance tests
  test/ExtendedXmlSerializer.Tests.Performance/Benchmarks.cs
  test/ExtendedXmlSerializer.Tests.Performance/ExtendedXmlSerializerTest.cs
  test/ExtendedXmlSerializer.Tests.Performance/LegacyExtendedXmlSerializerTest.cs
  test/ExtendedXmlSerializer.Tests.Performance/XmlSerializerTest.cs
Labels: hacktoberfest-accepted

#455 Scoped reference encounter counter to per-writer.
  src/ExtendedXmlSerializer/ExtensionModel/References/ReferenceEncounters.cs
  test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue454Tests.cs
Labels: bug

#465 Added basic support for custom `IDictionary<TKey, TValue>`.
  src/ExtendedXmlSerializer/ContentModel/Content/DictionaryEntries.cs
  src/ExtendedXmlSerializer/Core/DictionaryPairTypes.cs
  src/ExtendedXmlSerializer/ReflectionModel/DictionaryAdapters.cs
  src/ExtendedXmlSerializer/ReflectionModel/DictionaryAddDelegates.cs
  src/ExtendedXmlSerializer/ReflectionModel/DictionaryEnumerators.cs
  src/ExtendedXmlSerializer/ReflectionModel/DictionaryPairTypesLocator.cs
  src/ExtendedXmlSerializer/ReflectionModel/IDictionaryPairTypesLocator.cs
  test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue463Tests.cs
Labels: enhancement

#464 Skipped processing of parameterized-content members that have custom …
  src/ExtendedXmlSerializer/ExtensionModel/Content/Members/ParameterizedTypeMembers.cs
  test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue458Tests.cs
Labels: bug

#468 Generated API Key. 🤞
  .build/appveyor.yml
Labels: continuous integration
